### ISSUE TITLE
License on these images

### ISSUE THREAD

**Issue by Ybalrid** [ux3d/glTF-Sample-Environments#2]
Hello,

I am currently working on a model viewer for glTF assets, and I was wondering, what are the copyright/licensing information on these files, and can they be freely packaged and redistributed with an application (even like, being packaged directly inside the executable, with an appropriate copyright statement in like an "about" window somewhere if needed)?

**Comment by UX3D-nopper** [comment]
This is just a temporary solution. As soon as KTX2 and/or the IBL extensions are final, this repo will be closed. Then, it will be moved to the official Khronos repository.
The images used in the repo are linked to its original sources. Please feel free to download them there.
